apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-deploy
  labels:
    release: robusta
    app.kubernetes.io/name: test-deploy
    app.kubernetes.io/part-of: test
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deploy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
